spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pinstagram
    username: pinuser
    password: pinpassword
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
