version: "3.8"

services:
  # 로컬용 DB 구성
  # - 설정 참고: https://hub.docker.com/_/mariadb
  db:
    image: mariadb:10.6.4
    # application.properties에서 참조
    environment:
      MARIADB_DATABASE: jpadb
      MARIADB_ROOT_PASSWORD: "1111"
      MARIADB_USER: deokju
      MARIADB_PASSWORD: "1111"
    ports:
      - "3306:3306"